fix some issues
- add build_iso.sh and run.sh to help cos finish build and run
- soft linked boot_comp.c, share it with both i386 and x86_64
- other minor fixes

diff --git a/cos b/cos
--- a/cos
+++ b/cos
@@ -9,200 +9,153 @@ arch=
 
 initialize()
 {
-    case ${arch} in
-        x86_64 )
-            ;;
-        i386 )
-            ;;
-        * )
-            echo "Unsupported architecture"
-            exit 1
-    esac
+	case ${arch} in
+		x86_64 )
+		;;
+		i386 )
+		;;
+		* )
+		echo "Unsupported architecture"
+		exit 1
+	esac
 
-    echo "[cos setting arch] make -C src config-${arch}"
-    make -C src config-${arch} 
+	echo "[cos setting arch] make -C src config-${arch}"
+	make -C src config-${arch} 
 
-    echo "[cos executing] make -C src config init"
-    make -C src init
+	echo "[cos executing] make -C src config init"
+	make -C src init
 }
 
 build()
 {
-    if ! [ -r "src/.PLATFORM_ID" ]; then
-        echo "Must \"cos init\" before \"cos build\"."
-        exit 1
-    fi
+	if ! [ -r "src/.PLATFORM_ID" ]; then
+		echo "Must \"cos init\" before \"cos build\"."
+		exit 1
+	fi
 
-    echo "[cos executing] make -C src all"
-    make -C src all
+	echo "[cos executing] make -C src all"
+	make -C src all
 }
 
 clean()
 {
-    echo "[cos executing] make -C src clean"
-    make -C src distclean
+	echo "[cos executing] make -C src clean"
+	make -C src distclean
 }
 
 compose()
 {
-    if [ -z "$script" ] || [ -z "$name" ]; then
-	    usage
-    fi
+	if [ -z "$script" ] || [ -z "$name" ]; then
+		usage
+	fi
 
-    if ! [ -e "src/composer/target/debug/compose" ]; then
-        echo "Must \"cos build\" before composition. Could not find src/composer/target/debug/compose"
-        exit 1
-    fi
+	if ! [ -e "src/composer/target/debug/compose" ]; then
+		echo "Must \"cos build\" before composition. Could not find src/composer/target/debug/compose"
+	exit 1
+	fi
 
-    echo "[cos executing] src/composer/target/debug/compose $script $name"
-    src/composer/target/debug/compose $script $name
+	echo "[cos executing] src/composer/target/debug/compose $script $name"
+	src/composer/target/debug/compose $script $name
 
-    echo ""
-    echo "[cos generating ISO image]"
-    local dir="system_binaries/cos_build-${name}"
+	local dir="system_binaries/cos_build-${name}"
 
-    #detect grub-mkrescue/grub2-mkrescue
-    set +e
-    grub=$(command -v grub-mkrescue)
-    grub2=$(command -v grub2-mkrescue)
-    set -e
-    local grub_command=""
-    if [ "${grub}" != "" ]
-    then
-        grub_command="grub-mkrescue"
-    elif [ "${grub2}" != "" ]
-    then
-        grub_command="grub2-mkrescue"
-    else
-        echo "Cannot find grub-mkrescue/grub2-mkrescue to generate ISO image."
-        exit 1
-    fi
-
-    cd ${dir}
-    echo "set timeout=0" > grub.cfg
-    echo "set default=0" >> grub.cfg
-    echo "menuentry "composite" {" >> grub.cfg
-    echo "  multiboot2 /boot/cos.img" >> grub.cfg
-    echo "}" >> grub.cfg
-
-    mkdir -p iso/boot/grub
-    cp grub.cfg iso/boot/grub/
-    cp cos.img iso/boot/
-    ${grub_command} -d /usr/lib/grub/i386-pc -o ${name}.iso iso
-
-    #clean files
-    rm -rf iso grub.cfg
-
-    echo "Successfully generated ISO image: ${dir}/${name}.iso"
+	tools/build_iso.sh ${dir}/cos.img
 }
 
 run()
 {
-    local dir="./system_binaries/cos_build-${name}"
-    local num_sockets=1
-    local num_cores=1
-    local num_threads=1
-    local vcpus=$[${num_sockets}*${num_cores}*${num_threads}]
+	local dir="./system_binaries/cos_build-${name}"
 
-    if [ ! -f ${dir}/${name}.iso ]
-    then
-        echo "Cannot find ${name}.iso, please do compose first and check its name"
-        exit 1
-    fi
+	if [ ! -f ${dir}/cos.iso ]
+	then
+		echo "Cannot find cos.iso, please do compose first"
+		exit 1
+	fi
 
-    local elf_type=$(readelf -h ${dir}/cos.img | grep "Class:" | awk '{print $2}')
-    local kvm_flag=""
+	local elf_type=$(readelf -h ${dir}/cos.img | grep "Class:" | awk '{print $2}')
 
-    if [ -e "/dev/kvm" ] && [ -r "/dev/kvm" ] && [ -w "/dev/kvm" ]; then
-        kvm_flag="-enable-kvm"
-    fi
-
-    if [ "${elf_type}" == "ELF64" ]
-    then
-        qemu-system-x86_64 ${kvm_flag} -cpu max -smp ${vcpus},cores=${num_cores},threads=${num_threads},sockets=${num_sockets} -m 1024 -cdrom ${dir}/${name}.iso -no-reboot -nographic -s
-    elif [ "${elf_type}" == "ELF32" ]
-    then
-        qemu-system-i386 ${kvm_flag} -cpu max -smp ${vcpus},cores=${num_cores},threads=${num_threads},sockets=${num_sockets} -m 1024 -cdrom ${dir}/${name}.iso -no-reboot -nographic -s
-    else
-        echo "Unsupported image type!"
-    fi
+	if [ "${elf_type}" == "ELF64" ]
+	then
+		tools/run.sh ${dir}/cos.iso x86_64
+	elif [ "${elf_type}" == "ELF32" ]
+	then
+		tools/run.sh ${dir}/cos.iso i386
+	else
+		echo "Unsupported image type!"
+	fi
 }
 
 debug_run()
 {
-    local dir="system_binaries/cos_build-${name}"
-    local gdbinit="system_binaries/gdbinit"
-    local num_sockets=1
-    local num_cores=1
-    local num_threads=1
-    local vcpus=$[${num_sockets}*${num_cores}*${num_threads}]
+	local dir="system_binaries/cos_build-${name}"
+	local gdbinit="system_binaries/gdbinit"
 
-    if [ ! -f ${dir}/${name}.iso ]
-    then
-        echo "Cannot find ${name}.iso, please do compose first and check its name"
-        exit 1
-    fi
+	if [ ! -f ${dir}/cos.iso ]
+	then
+		echo "Cannot find cos.iso, please do compose first and check its name"
+		exit 1
+	fi
 
-    if [ ! -f ${gdbinit} ]
-    then
-        echo "set confirm off" > ${gdbinit}
-        echo "#file ${dir}/global.booter/no_interface.llbooter.global.booter" >> ${gdbinit}
-        echo "file ${dir}/cos.img" >> ${gdbinit}
-        echo "target remote:1234" >> ${gdbinit}
-    fi
+	if [ ! -f ${gdbinit} ]
+	then
+		echo "set confirm off" > ${gdbinit}
+		echo "#file ${dir}/global.booter/no_interface.llbooter.global.booter" >> ${gdbinit}
+		echo "file ${dir}/cos.img" >> ${gdbinit}
+		echo "target remote:1234" >> ${gdbinit}
+	fi
 
-    local elf_type=$(readelf -h ${dir}/cos.img | grep "Class:" | awk '{print $2}')
+	local elf_type=$(readelf -h ${dir}/cos.img | grep "Class:" | awk '{print $2}')
 
-    if [ "${elf_type}" == "ELF64" ]
-    then
-        qemu-system-x86_64 -cpu max -smp ${vcpus},cores=${num_cores},threads=${num_threads},sockets=${num_sockets} -m 1024 -cdrom ${dir}/${name}.iso -no-reboot -nographic -s -S
-    elif [ "${elf_type}" == "ELF32" ]
-    then
-        qemu-system-i386 -cpu max -smp ${vcpus},cores=${num_cores},threads=${num_threads},sockets=${num_sockets} -m 1024 -cdrom ${dir}/${name}.iso -no-reboot -nographic -s -S
-    else
-        echo "Unsupported image type!"
-    fi
+	if [ "${elf_type}" == "ELF64" ]
+	then
+		tools/run.sh ${dir}/cos.iso x86_64 debug
+	elif [ "${elf_type}" == "ELF32" ]
+	then
+		tools/run.sh ${dir}/cos.iso i386 debug
+	else
+		echo "Unsupported image type!"
+	fi
 }
 
 gdb()
 {
-    command gdb -x ./system_binaries/gdbinit
+	command gdb -x ./system_binaries/gdbinit
 }
 
 usage()
 {
-    echo "Usage: " $0 " init <arch: [x86_64|i386]>|build|clean|compose <script> <output name>|run <composite name>|debug_run <composite name>|gdb"
-    exit 1
+	echo "Usage: " $0 " init <arch: [x86_64|i386]>|build|clean|compose <script> <output name>|run <composite name>|debug_run <composite name>|gdb"
+	exit 1
 }
 
 case $1 in
-    init )
-        arch=$2
-        initialize
-        ;;
-    build )
-        build
-        ;;
-    clean )
-        clean
-        ;;
-    compose )
-        script=$2
-        name=$3
-        compose
-        ;;
-    run )
-        binary=$2
-        name=$2
-        run
-        ;;
-    debug_run )
-        name=$2
-        debug_run
-        ;;
-    gdb )
-        gdb
-        ;;
-    * )
-        usage
+	init )
+		arch=$2
+		initialize
+		;;
+	build )
+		build
+		;;
+	clean )
+		clean
+		;;
+	compose )
+		script=$2
+		name=$3
+		compose
+		;;
+	run )
+		binary=$2
+		name=$2
+		run
+		;;
+	debug_run )
+		name=$2
+		debug_run
+		;;
+	gdb )
+		gdb
+		;;
+	* )
+		usage
 esac
