improve cos script

diff --git a/cos b/cos
--- a/cos
+++ b/cos
@@ -1,14 +1,36 @@
 #!/bin/bash
 
+set -e
+
 script=
 name=
 binary=
+arch=
+
+initialize()
+{
+    case ${arch} in
+        x86_64 )
+            ;;
+        i386 )
+            ;;
+        * )
+            echo "Unsupported architecture"
+            exit 1
+    esac
+
+    echo "[cos setting arch] make -C src config-${arch}"
+    make -C src config-${arch} 
+
+    echo "[cos executing] make -C src config init"
+    make -C src init
+}
 
 build()
 {
     if ! [ -r "src/.PLATFORM_ID" ]; then
-	echo "Must \"cos init\" before \"cos build\"."
-	exit 2
+        echo "Must \"cos init\" before \"cos build\"."
+        exit 1
     fi
 
     echo "[cos executing] make -C src all"
@@ -17,88 +39,143 @@ build()
 
 clean()
 {
-    echo "[cos executing] make -C clean"
-    make -C src clean
-}
-
-distclean()
-{
-    echo "[cos executing] make -C distclean"
+    echo "[cos executing] make -C src clean"
     make -C src distclean
-}
-
-initialize()
-{
-    echo "[cos executing] make -C src config init"
-    make -C src config init
-}
-
-usage()
-{
-    echo "Usage: " $0 " init|build|reset|distclean|compose <script> <output name>|run <binary>"
-    exit 2
 }
 
 compose()
 {
     if [ -z "$script" ] || [ -z "$name" ]; then
-	usage
+	    usage
     fi
+
     if ! [ -e "src/composer/target/debug/compose" ]; then
-	echo "Must \"cos build\" before composition. Could not find src/composer/target/debug/compose"
-	exit 2
+        echo "Must \"cos build\" before composition. Could not find src/composer/target/debug/compose"
+        exit 1
     fi
+
     echo "[cos executing] src/composer/target/debug/compose $script $name"
     src/composer/target/debug/compose $script $name
+
+    echo ""
+    echo "[cos generating ISO image]"
+    local dir="system_binaries/cos_build-${name}"
+
+    cd ${dir}
+    echo "set timeout=0" > grub.cfg
+    echo "set default=0" >> grub.cfg
+    echo "menuentry "kernel" {" >> grub.cfg
+    echo "  multiboot2 /boot/cos.img" >> grub.cfg
+    echo "}" >> grub.cfg
+
+    mkdir -p iso/boot/grub
+    cp grub.cfg iso/boot/grub/
+    cp cos.img iso/boot/
+    grub-mkrescue -o ${name}.iso iso
+    #clean files
+    rm -rf iso grub.cfg
+
+    echo "Successfully generate ISO image: ${dir}/${name}.iso"
 }
 
 run()
 {
-    local dir=$(dirname ${binary})  
-    local binary_name=$(basename ${binary})
-    local cur_dir=$(pwd)
-    local elf_type=$(readelf -h ${binary} | grep "Class:" | awk '{print $2}')
+    local dir="./system_binaries/cos_build-${name}"  
+    if [ ! -f ${dir}/${name}.iso ]
+    then
+        echo "Cannot find ${name}.iso, please do compose first and check its name"
+        exit 1
+    fi
+
+    local elf_type=$(readelf -h ${dir}/cos.img | grep "Class:" | awk '{print $2}')
+    local kvm_flag=""
+
+    if [ -e "/dev/kvm" ] && [ -r "/dev/kvm" ] && [ -w "/dev/kvm" ]; then
+        kvm_flag="-enable-kvm"
+    fi
 
     if [ "${elf_type}" == "ELF64" ]
     then
-        #create grub.cfg 
-        cd ${dir}
-        echo "set timeout=0" > grub.cfg
-        echo "set default=0" >> grub.cfg
-        echo "menuentry "kernel" {" >> grub.cfg
-        echo "  multiboot2 /boot/${binary_name}" >> grub.cfg
-        echo "}" >> grub.cfg
-
-        mkdir -p iso/boot/grub
-        cp grub.cfg iso/boot/grub/
-        cp ${binary_name} iso/boot/
-        grub-mkrescue -o kernel.iso iso
-
-        qemu-system-x86_64 -cpu max -m 1024 -cdrom kernel.iso -no-reboot -nographic -s
+        qemu-system-x86_64 ${kvm_flag} -cpu host -m 1024 -cdrom ${dir}/${name}.iso -no-reboot -nographic -s
     elif [ "${elf_type}" == "ELF32" ]
     then
-        echo "[cos executing] tools/run.sh $binary"
-        tools/run.sh $binary
+        qemu-system-i386 ${kvm_flag} -cpu host -m 1024 -cdrom ${dir}/${name}.iso -no-reboot -nographic -s
     else
-        echo "unsupported image type!"
+        echo "Unsupported image type!"
     fi
 }
 
+debug_run()
+{
+    local dir="system_binaries/cos_build-${name}"
+    local gdbinit="system_binaries/gdbinit"
+
+    if [ ! -f ${dir}/${name}.iso ]
+    then
+        echo "Cannot find ${name}.iso, please do compose first and check its name"
+        exit 1
+    fi
+
+    if [ ! -f ${gdbinit} ]
+    then
+        echo "set confirm off" > ${gdbinit}
+        echo "#file ${dir}/global.booter/no_interface.llbooter.global.booter" >> ${gdbinit}
+        echo "file ${dir}/cos.img" >> ${gdbinit}
+        echo "target remote:1234" >> ${gdbinit}
+    fi
+
+    local elf_type=$(readelf -h ${dir}/cos.img | grep "Class:" | awk '{print $2}')
+
+    if [ "${elf_type}" == "ELF64" ]
+    then
+        qemu-system-x86_64 -cpu max -m 1024 -cdrom ${dir}/${name}.iso -no-reboot -nographic -s -S
+    elif [ "${elf_type}" == "ELF32" ]
+    then
+        qemu-system-i386 -cpu max -m 1024 -cdrom ${dir}/${name}.iso -no-reboot -nographic -s -S
+    else
+        echo "Unsupported image type!"
+    fi
+}
+
+gdb()
+{
+    command gdb -x ./system_binaries/gdbinit
+}
+
+usage()
+{
+    echo "Usage: " $0 " init <arch: [x86_64|i386]>|build|clean|compose <script> <output name>|run <composite name>|debug_run <composite name>|gdb"
+    exit 1
+}
+
 case $1 in
-    init )    initialize
-	      ;;
-    build )   build
-	      ;;
-    reset )   clean
-	      ;;
-    distclean ) distclean
-          ;;
-    compose ) script=$2
-	      name=$3
-	      compose
-	      ;;
-    run )     binary=$2
-	      run
-	      ;;
-    * )       usage
+    init )
+        arch=$2
+        initialize
+        ;;
+    build )
+        build
+        ;;
+    clean )
+        clean
+        ;;
+    compose )
+        script=$2
+        name=$3
+        compose
+        ;;
+    run )
+        binary=$2
+        name=$2
+        run
+        ;;
+    debug_run )
+        name=$2
+        debug_run
+        ;;
+    gdb )
+        gdb
+        ;;
+    * )
+        usage
 esac
